apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ubuntu
  name: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - name: ubuntu
          image: busybox:latest
          command:
          - sleep
          - "86400"
          volumeMounts:
            - mountPath: /shared_files
              name: test-vol
  volumeClaimTemplates:
  - metadata: 
      name: test-vol
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: "longhorn"
